<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <RootNamespace>MilkyFrog.Platform.Windows</RootNamespace>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MilkyFrog.Core\MilkyFrog.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference
      Include="NAudio"
      Version="2.2.1" />
  </ItemGroup>

</Project>